// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* F:\dell-pc\Documents\GitHub\MyAutomatic\WinNTKline\gSOAPverify\soap\myweb.h
   Generated by wsdl2h 2.8.30 from F:\dell-pc\Documents\GitHub\MyAutomatic\WinNTKline\gSOAPverify\soap\myweb.wsdl and typemap.dat
   2016-10-17 14:47:08 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on F:\dell-pc\Documents\GitHub\MyAutomatic\WinNTKline\gSOAPverify\soap\myweb.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stl.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://localhost/myweb.wsdl                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $CONTAINER                                                                 *
 *   std::vector                                                              *
 *                                                                            *
\******************************************************************************/
//template <class T> class std::vector;
	#include <string>
/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/

//#import "stl.h"	// enable STL containers when used (option -s removes STL dependency)

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://localhost/myweb.wsdl"
ns2 = "urn:myweb"

*/

#define SOAP_NAMESPACE_OF_ns2	"urn:myweb"
//gsoap ns2   schema namespace:	urn:myweb
//gsoap ns2   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/

/// Primitive built-in type "wsdl:xsd-int".
typedef std::string wsdl__xsd_int;

//gsoap wsdl  schema namespace:	http://www.w3.org/ns/wsdl

/// Primitive built-in type "wsdl:xsd-string".
typedef std::string wsdl__xsd_string;


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/



/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   urn:myweb                                                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   urn:myweb                                                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   urn:myweb                                                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   urn:myweb                                                                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns2  service name:	myweb 
//gsoap ns2  service type:	mywebPortType 
//gsoap ns2  service port:	http://localhost/myweb.cgi 
//gsoap ns2  service port:	http://localhost/myweb.cgi/myweb.cgi 
//gsoap ns2  service namespace:	urn:myweb 
//gsoap ns2  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage myweb Definitions

@section myweb_bindings Service Bindings

  - @ref myweb

@section myweb_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page myweb Binding "myweb"

@section myweb_service Service Documentation "myweb"
gSOAP 2.8.30 generated service definition

@section myweb_operations Operations of Binding "myweb"

  - @ref ns2__encrypt

  - @ref ns2__login_by_key

@section myweb_ports Endpoints of Binding "myweb"

  - http://localhost/myweb.cgi

  - http://localhost/myweb.cgi/myweb.cgi

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   myweb                                                                    *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__encrypt                                                             *
 *                                                                            *
\******************************************************************************/


/** Operation "ns2__encrypt" of service binding "myweb".
Service definition of function api__encrypt

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__encrypt(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    std::string                         input,
    // output parameters:
    std::string                        &output
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__encrypt(
    struct soap *soap,
    // input parameters:
    std::string                         input,
    // output parameters:
    std::string                        &output
  );
@endcode

C++ proxy class (defined in soapmywebProxy.h):
@code
  class mywebProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapmywebService.h):
@code
  class mywebService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns2  service method-protocol:	encrypt SOAP
//gsoap ns2  service method-style:	encrypt rpc
//gsoap ns2  service method-encoding:	encrypt http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	encrypt ""
//gsoap ns2  service method-output-action:	encrypt Response
int ns2__encrypt(
    std::string                         input,	///< Input parameter
    std::string                        &output	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   ns2__login_by_key                                                        *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__login_by_keyResponse" of operation "ns2__login_by_key".
struct ns2__login_by_keyResponse
{
    wsdl__xsd_int                       flag;
    wsdl__xsd_int                       id;
    wsdl__xsd_int                       age;
    wsdl__xsd_string                    user;
    wsdl__xsd_string                    email;
};

/** Operation "ns2__login_by_key" of service binding "myweb".
Service definition of function api__login_by_key

  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"

  - Addressing input action: ""

  - Addressing output action: "Response"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__login_by_key(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    wsdl__xsd_string                    usr,
    wsdl__xsd_string                    psw,
    // output parameters:
    struct ns2__login_by_keyResponse&
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__login_by_key(
    struct soap *soap,
    // input parameters:
    wsdl__xsd_string                    usr,
    wsdl__xsd_string                    psw,
    // output parameters:
    struct ns2__login_by_keyResponse&
  );
@endcode

C++ proxy class (defined in soapmywebProxy.h):
@code
  class mywebProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapmywebService.h):
@code
  class mywebService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns2  service method-protocol:	login_by_key SOAP
//gsoap ns2  service method-style:	login_by_key rpc
//gsoap ns2  service method-encoding:	login_by_key http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	login_by_key ""
//gsoap ns2  service method-output-action:	login_by_key Response
int ns2__login_by_key(
    wsdl__xsd_string                    usr,	///< Input parameter
    wsdl__xsd_string                    psw,	///< Input parameter
    struct ns2__login_by_keyResponse   &	///< Output response struct parameter
);

/**

@page myweb Binding "myweb"

@section myweb_policy_enablers Policy Enablers of Binding "myweb"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns2 Top-level root elements of schema "urn:myweb"

*/

/* End of F:\dell-pc\Documents\GitHub\MyAutomatic\WinNTKline\gSOAPverify\soap\myweb.h */
