/* soapmywebProxy.h
   Generated by gSOAP 2.8.106 for rpcapi.h

gSOAP XML Web services tools
Copyright (C) 2000-2020, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapmywebProxy_H
#define soapmywebProxy_H
#include "soapH.h"

    class SOAP_CMAC mywebProxy : public soap {
      public:
        /// Endpoint URL of service 'mywebProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in rpcapi.h, if any
        /// Construct a proxy with new managing context
        mywebProxy();
        /// Copy constructor
        mywebProxy(const mywebProxy& rhs);
        /// Construct proxy given a managing context
        mywebProxy(const struct soap&);
        /// Construct proxy given a managing context and endpoint URL
        mywebProxy(const struct soap&, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        mywebProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        mywebProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        mywebProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        mywebProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context
        virtual ~mywebProxy();
        /// Initializer used by constructors
        virtual void mywebProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual mywebProxy *copy();
        /// Copy assignment
        mywebProxy& operator=(const mywebProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'trans' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int trans(char *msg, char **rtn) { return this->trans(NULL, NULL, msg, rtn); }
        /// Web service synchronous operation 'trans' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int trans(const char *soap_endpoint_url, const char *soap_action, char *msg, char **rtn) { return this->send_trans(soap_endpoint_url, soap_action, msg) || this->recv_trans(rtn) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_trans' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_trans(const char *soap_endpoint_url, const char *soap_action, char *msg);
        /// Web service asynchronous operation 'recv_trans' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_trans(char **rtn);
        //
        /// Web service synchronous operation 'get-server-status' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int get_server_status(char *req, char *&rsp) { return this->get_server_status(NULL, NULL, req, rsp); }
        /// Web service synchronous operation 'get-server-status' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int get_server_status(const char *soap_endpoint_url, const char *soap_action, char *req, char *&rsp) { return this->send_get_server_status(soap_endpoint_url, soap_action, req) || this->recv_get_server_status(rsp) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_get-server-status' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_get_server_status(const char *soap_endpoint_url, const char *soap_action, char *req);
        /// Web service asynchronous operation 'recv_get-server-status' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_get_server_status(char *&rsp);
        //
        /// Web service synchronous operation 'login-by-key' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int login_by_key(char *usr, char *psw, struct api__ArrayOfEmp2 &stat) { return this->login_by_key(NULL, NULL, usr, psw, stat); }
        /// Web service synchronous operation 'login-by-key' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int login_by_key(const char *soap_endpoint_url, const char *soap_action, char *usr, char *psw, struct api__ArrayOfEmp2 &stat) { return this->send_login_by_key(soap_endpoint_url, soap_action, usr, psw) || this->recv_login_by_key(stat) ? this->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_login-by-key' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_login_by_key(const char *soap_endpoint_url, const char *soap_action, char *usr, char *psw);
        /// Web service asynchronous operation 'recv_login-by-key' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_login_by_key(struct api__ArrayOfEmp2 &stat);
    };
#endif
