CMAKE_MINIMUM_REQUIRED(VERSION 2.8...3.6)

SET(BUILD_TIME_SEEK_LIB 0)

IF (NOT BUILD_TIME_SEEK_LIB)
    PROJECT(timeTest)
ELSE ()
    PROJECT(timeUtil)
ENDIF ()

SET(CMAKE_BUILD_TYPE Debug CACHE STRING "set build type to debug" FORCE)
#SET(CMAKE_BUILD_TYPE Release CACHE STRING "set build type to release" FORCE)

SET(CMAKE_CXX_STANDARD 11)
CMAKE_POLICY(SET CMP0020 NEW)

INCLUDE_DIRECTORIES(..)
SET(SOURCE_FILES TimeSeek.cpp TimeDbMgr.cpp)

ADD_DEFINITIONS(-DTIMESEEK)

SET(TARGET_NAME ${PROJECT_NAME})
IF (NOT BUILD_TIME_SEEK_LIB)
    ADD_EXECUTABLE(${PROJECT_NAME} ${SOURCE_FILES} main.cpp)
ELSE ()
    ADD_LIBRARY(${PROJECT_NAME} SHARED ${SOURCE_FILES})
    SET(TARGET_NAME lib${PROJECT_NAME}.so)
ENDIF ()

SET(EXTRA_LIBS pthread)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${EXTRA_LIBS})
ADD_CUSTOM_COMMAND(
    TARGET ${PROJECT_NAME}
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory ${EXEC_PATH}
    COMMAND ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME} ${EXEC_PATH}
    COMMAND ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_SOURCE_DIR}/time.cfg ${EXEC_PATH}
)
