# C/C++ with GCC – CI pipeline

trigger:
  - auto-dev

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      set -e
      ./build.sh all -j
    displayName: 'Build LinxSrvc'

  - script: |
      set -e
      ./build.sh QtGames/
    displayName: 'Build QtGames'

  - script: |
      set -e
      ./build.sh test
    displayName: 'Test & coverage'

  - script: |
      ./build.sh clean
    displayName: 'Clean workspace'
    condition: always()
