CMAKE_MINIMUM_REQUIRED(VERSION 2.8...3.16)

SET(PROJ_NAME lookup)
PROJECT(${PROJ_NAME} C CXX)
FILE(GLOB SOURCE_FILES "*.c*")
SET(EXTRA_LIBS pthread)
SET(EXEC_PATH ${CMAKE_CURRENT_SOURCE_DIR}/../gen)

ADD_EXECUTABLE(${PROJ_NAME} ${SOURCE_FILES})
TARGET_LINK_LIBRARIES(${PROJ_NAME} ${EXTRA_LIBS})
ADD_CUSTOM_COMMAND(
    TARGET ${PROJ_NAME}
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory ${EXEC_PATH}
    COMMAND ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_BINARY_DIR}/${PROJ_NAME} ${EXEC_PATH}
)
