# 数据配置
data:
  custom_dataset: true  # 是否使用自定义数据集
  train_path: ./data/train.txt  # 自定义训练集路径
  val_path: ./data/val.txt  # 自定义验证集路径
  dataset_name: wikitext  # Hugging Face 数据集名称（当 custom_dataset=false 时使用）
  max_seq_length: 1024
  num_workers: 4

# 模型配置
model:
  model_name: bert  # 默认模型
  tokenizer_name: bert  # 分词器
  deepseek_model_name: deepseek-ai/deepseek-model  # DeepSeek
  local_model_path:  ~/.cache/modelscope/hub/models/deepseek-ai/DeepSeek-R1-Distill-Llama-8B  # 本地模型路径 (当 custom_model=true 时有效)
  tokenizer_path: "../../../bert-base-uncased"  # 分词器路径
  model_path: "../../../bert-base-uncased" # 模型路径
  use_deepseek: false  # 是否使用 DeepSeek 模型
  params:
    vocab_size: 102400
    hidden_size: 4096
    num_hidden_layers: 32
    num_attention_heads: 32
    intermediate_size: 11008
    max_position_embeddings: 4096
    rope_theta: 10000.0
    tie_word_embeddings: false

# 训练配置
training:
  epochs: 10
  batch_size: 8
  val_batch_size: 16
  fp16: true
  grad_clip: 1.0
  out_dir: ../gen/train/outs
  save_interval: 1
  early_stop_patience: 3
  lr: 5e-5
  weight_decay: 0.01
  use_lora: false  # 是否使用 LoRA 微调

# LoRA 配置
lora:
  r: 8
  lora_alpha: 16
  target_modules: ["q_proj", "v_proj"]
  lora_dropout: 0.1

# 学习率调度
scheduler:
  type: linear
  warmup_steps: 1000

# 日志配置
logging:
  log_dir: ../gen/train/logs
