; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

; Generated by VC++ for Common Language Runtime
.file "E:\buffer\Temp\tmp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
