CMAKE_MINIMUM_REQUIRED(VERSION 2.8...3.16)

PROJECT(genSeek CXX)
SET(CMAKE_CXX_STANDARD 11)

ADD_DEFINITIONS("-Wall -g -Wno-unused-function")

INCLUDE_DIRECTORIES(..)

SET(SOURCE_FILES main.cpp)
ADD_EXECUTABLE(${PROJECT_NAME} ${SOURCE_FILES})

IF(NOT WIN32)
    TARGET_LINK_LIBRARIES(${PROJECT_NAME} pthread)
ENDIF()

ADD_CUSTOM_COMMAND(
    TARGET ${PROJECT_NAME}
    POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory ${EXEC_PATH}
    COMMAND ${CMAKE_COMMAND} -E copy_if_different ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME} ${EXEC_PATH}
)
